language: python
python:
  - 3.5
  - 3.6
install:
  - pip install -r base_requirements.txt
  - pip install -U pytest==3.0.5 pytest-cov coveralls flake8
  - pip install sqlalchemy
script:
  - flake8 .
  - python -m pytest --cov .
after_success:
  - coveralls
